/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1edd;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel1.setText("Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 60, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel2.setText("Proyecto 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        int count = 0;
        String[] lines = cargardatos().split("\n");
        UsersList userslist = new UsersList();
        AdjList adjlist = new AdjList();
        for(int i =1; i<lines.length;i++){
            if(lines[i].equals("")){
               count = i+2;
               break;
            }
            else{
               String[] usuarios = lines[i].split(", ");
               int number = Integer.parseInt(usuarios[0]);
               String name = usuarios[1];
               userslist.insert(number, name);
            }
        }
        for(int j = count;j<lines.length;j++){ 
                 User inicial = new User(0,"");
                 User usuariodestino = new User(0,"");
                 String[] relaciones = lines[j].split(", ");
                 int idinicial = Integer.parseInt(relaciones[0]);
                 int iddestino = Integer.parseInt(relaciones[1]);
                 int peso = Integer.parseInt(relaciones[2]);
                 User aux1 = userslist.pFirst;
                 while(aux1!=null){ 
                         if(idinicial==aux1.getNumber()){ 
                                  inicial = aux1;
                                  break;
                          }else{ 
                                  aux1 = aux1.pnext;
                         }
                 }
                 User aux2 = userslist.pFirst;
                 while(aux2!=null){    
                         if(iddestino == aux2.getNumber()){
                                  usuariodestino = aux2;
                                  break;
                         }else{
                                  aux2 = aux2.pnext;
                                  
                         }
                 }
                 if(adjlist.isEmpty()||!adjlist.existeinicial(idinicial)){
                         Destino destino = new Destino(usuariodestino,peso);
                         RelationsList relationslist = new RelationsList(inicial,destino);
                         adjlist.insert(relationslist);
                         
                 }
                 else{
                         Destino destino = new Destino(usuariodestino,peso);
                         RelationsList aux = adjlist.pFirst;
                         while(aux!=null){
                                  if(aux.inicial.number == idinicial){
                                          aux.insertdestino(destino);
                                          break;
                                  }else{
                                           aux = aux.pnext;
                                  }
                          }
                
                 }
            
        }
        adjlist.print();
}
         
    
    public static String cargardatos() {
  String aux="";   
  String texto="";
  try{
   JFileChooser file=new JFileChooser();
   file.showOpenDialog(file);
   File abre=file.getSelectedFile();
   if(abre!=null){     
      FileReader archivos=new FileReader(abre);
      BufferedReader lee=new BufferedReader(archivos);
      while((aux=lee.readLine())!=null)
      {
         texto+= aux+ "\n";
      }
         lee.close();
    }    
   }
   catch(IOException ex){
     JOptionPane.showMessageDialog(null,ex+"" +
           "\nNo se ha encontrado el archivo",
                 "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
    }
  return texto;//El texto se almacena en el JTextArea

    }//GEN-LAST:event_btnCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
