/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1edd;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.FileWriter;

/**
 *
 * @author rodri
 */
public class Menu extends javax.swing.JFrame {
    String texto;
    int count;
    UsersList userslist;
    RelationsList relationslist;
    AdjList adjlist;
    /**
     * Creates new form Menu
     * @param texto
     */
    public Menu() {
        initComponents();
        this.texto = "";
        this.count =0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        btnAgregarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        btnAgregarUsuario1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel1.setText("Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 60, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel2.setText("Proyecto 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        btnAgregarUsuario.setText("Salir");
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        btnEliminarUsuario.setText("Eliminar Usuario");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        btnAgregarUsuario1.setText("Agregar Usuario");
        btnAgregarUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 113, 300, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        texto = "";
        cargardatos();
        count =0;
        String[] lines = texto.split("\n");
        userslist = new UsersList();
        adjlist = new AdjList();
        for(int i =0; i<lines.length;i++){
            if(lines[i].equals("Relaciones")){
                count=i;
                break;
            }
            if(!lines[i].equals("")&&!lines[i].equals("Usuarios")){
               String[] usuarios = lines[i].split(", ");
               int number = Integer.parseInt(usuarios[0]);
               String name = usuarios[1];
               userslist.insert(number, name);
            }
        }
        for(int j = count+1;j<lines.length;j++){ 
            if(!lines[j].equals("")){
                 User inicial = new User(0,"");
                 User usuariodestino = new User(0,"");
                 String[] relaciones = lines[j].split(", ");
                 int idinicial = Integer.parseInt(relaciones[0]);
                 int iddestino = Integer.parseInt(relaciones[1]);
                 int peso = Integer.parseInt(relaciones[2]);
                 User aux1 = userslist.pFirst;
                 while(aux1!=null){ 
                         if(idinicial==aux1.getNumber()){ 
                                  inicial = aux1;
                                  break;
                          }else{ 
                                  aux1 = aux1.pnext;
                         }
                 }
                 User aux2 = userslist.pFirst;
                 while(aux2!=null){    
                         if(iddestino == aux2.getNumber()){
                                  usuariodestino = aux2;
                                  break;
                         }else{
                                  aux2 = aux2.pnext;
                                  
                         }
                 }
                 if(adjlist.isEmpty()||!adjlist.existeinicial(idinicial)){
                         Destino destino = new Destino(usuariodestino,peso);
                         relationslist = new RelationsList(inicial,destino);
                         adjlist.insert(relationslist);
                         
                 }
                 else{
                         Destino destino = new Destino(usuariodestino,peso);
                         RelationsList aux = adjlist.pFirst;
                         while(aux!=null){
                                  if(aux.inicial.number == idinicial){
                                          aux.insertdestino(destino);
                                          break;
                                  }else{
                                           aux = aux.pnext;
                                  }
                          }
                
                 }
            }
        }
        adjlist.print();
}
    
            
    
    public String cargardatos() {
  String aux="";   
  try{
   JFileChooser file=new JFileChooser();
   file.showOpenDialog(file);
   File abre=file.getSelectedFile();
   if(abre!=null){     
      FileReader archivos=new FileReader(abre);
      BufferedReader lee=new BufferedReader(archivos);
      while((aux=lee.readLine())!=null)
      {
         this.texto+= aux+ "\n";
      }
         lee.close();
    }    
   }
   catch(IOException ex){
     JOptionPane.showMessageDialog(null,ex+"" +
           "\nNo se ha encontrado el archivo",
                 "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
    }
  return this.texto;//El texto se almacena en el JTextArea

    }//GEN-LAST:event_btnCargarActionPerformed

    
    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    public boolean isNumeric(String usuarioaeliminar){
	try {
		Integer.valueOf(usuarioaeliminar);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
    }
    
    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        // TODO add your handling code here:
       String usuarioaeliminar;
       while (true){
           usuarioaeliminar = JOptionPane.showInputDialog("Ingrese el ID del usuario a eliminar");
           if (isNumeric(usuarioaeliminar) == false || !userslist.isUser(Integer.parseInt(usuarioaeliminar))){
               JOptionPane.showMessageDialog(null,"Error, debe ingresar un numero correspondiente a un usuario.");
               break;
           }else{
               break;
           }
       }
      String[] lines = texto.split("\n");
      for(int j =1;j<count;j++){
        if(!lines[j].equals("")||!lines[j].equals("")){
            String[] elements = lines[j].split(", ");
            if(elements[0].equals(usuarioaeliminar)){
                this.texto = texto.replaceAll(lines[j],"");
            }
        }
      }
       for( int i = count+1; i<lines.length;i++){
           if(!lines[i].equals("")&&!lines[i].equals("Relaciones")){
                String[] elements = lines[i].split(", ");
               if(elements[0].equals(usuarioaeliminar)||elements[1].equals(usuarioaeliminar)){
                   this.texto = texto.replaceAll(lines[i], ""); 
               }
          }
       }
        System.out.println(texto);
       try {
      File myObj = new File("C:\\Users\\rodri\\Desktop\\Usuarios.txt");
      FileWriter myWriter = new FileWriter(myObj);
      myWriter.write(texto);
      myWriter.close();
      JOptionPane.showMessageDialog(rootPane, "Usuario "+usuarioaeliminar+" eliminado correctamente");
    } catch (IOException e) {
      JOptionPane.showMessageDialog(rootPane, "Error");
      e.printStackTrace();
    }
       
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnAgregarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuario1ActionPerformed
        // TODO add your handling code here:
        MenuAgregar menuagregar = new MenuAgregar(texto,userslist,relationslist,adjlist);
        menuagregar.setVisible(true);
        menuagregar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAgregarUsuario1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnAgregarUsuario1;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
